set_property SRC_FILE_INFO {cfile:C:/Users/Saad/Desktop/stingray/arm_fpga_04_hdmi_output/arm_fpga_04_hdmi_output.srcs/constrs_1/new/hdmi.xdc rfile:../../../arm_fpga_04_hdmi_output.srcs/constrs_1/new/hdmi.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H18 [get_ports {HDMI_EN[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H16 [get_ports TMDS_clk_p]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D19 [get_ports {TMDS_data_p[0]}]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C20 [get_ports {TMDS_data_p[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B19 [get_ports {TMDS_data_p[2]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E18 [get_ports {HDMI_HPD_tri_i[0]}]
